### ISSUE TITLE
Rich Presence Is Not Showing Up 

### ISSUE THREAD

**Issue by craneinbush** [AkkozaDevelops/PCStats-Rich-Presence#3]
Opened up the file and put it on the run on startup but it doesn't work, I followed the instructions but I may have messed something up.

**Comment by AkkozaDevelops** [comment]
You have to have your playing status on

also sorry for the really really late reply, I haven't signed onto GitHub for a little while!

**Comment by craneinbush** [comment]
Hmm, I'm not sure still, do you mind if I add you on Discord?

**Comment by AkkozaDevelops** [comment]
Yeah, go ahead.

Akkoza#8767
